### PR TITLE
Use enum for KerML checksum algorithms

### LINKED ISSUE #33: Produce explanatory error messages on lexer/parser failure
Currently lexing/parsing errors produce very short errors, without reference to the source code. This means that `sysand include` and `sysand build` may fail in ways that are hard to understand and debug for the user.

Error messages should at a minimum show the offending part of the code, in which file it appears, and ideally contain a longer, human readable, explanation of the error.

### LINKED ISSUE #112: Consider adding end-of-file newline when printing human readable JSON
Currently, command `sysand init` creates `.meta.json` without a newline at the end of the file. This behavior is an annoying paper cut for users because git and GitHub “complains” about that:

Image

We should consider adding a newline at the end of human readable JSONs.

### LINKED ISSUE #122: Simplify setting metamodel field
Currently, the command for setting metamodel `sysand info metamodel --set` accepts an arbitrary string and it is left for the user to know what values are valid here. We should add an explicit command for setting the metamodel that helps the user to get this right by accepting two arguments instead of an arbitrary string:

1. `--sysml` or `--kerml` to specify for which language is the metamodel.
2. `--release` to specify the release number defaulting to `20250201`, which is the stable release.

### PR DESCRIPTION
**Pull request by andrius-puksta-sensmetry**
## Changes

- style: consistently use `` for quoting everything (mostly IRIs). This is consistent with how Cargo
  uses quoting in output
- use `serialization` instead of `serialisation` to match common usage other crates/ecosystems
- use an enum for valid sysml/kerml file checksum algorithms, since the list is short and fixed
- always append newline to generated `.project.json` and `.meta.json`. Fixes #112.
- remove Beta1 (20230201) std lib metadata

## CLI improvements

- improve error and log messages in many places
- correctly strip color and other styling from text in tests, when using pipes, etc. with `anstream`. It's already used by default in `env_logger`, so the only place where we used color unconditionally was in `sysand/src/main.rs`
- don't panic when including invalid sysml/kerml files; give proper errors instead. Fixes #33. Example:
```console
$ echo \"hello\" > a.sysml
$ sysand include a.sysml
error: failed to extract symbol names from `a.sysml`: error at line 1, byte 1:
`"hello"`: unexpected string
```
- improve experience of setting the project metamodel with `sysand info metamodel`. Closes #122. Current help output:
```console
$ sysand info metamodel --help
Get or set the metamodel of the project

Usage: sysand info metamodel [OPTIONS]

Options:
      --set <KIND>
          Set a SysML v2 or KerML metamodel. To set a custom metamodel, use `--set-custom`

          Possible values:
          - sysml: SysML v2 metamodel. Identifier: `https://www.omg.org/spec/SysML/<release>`
          - kerml: KerML metamodel. Identifier: `https://www.omg.org/spec/KerML/<release>`

      --release <YYYYMMDD>
          Choose the release of the SysML v2 or KerML metamodel.
          SysML 2.0 and KerML 1.0 have the same release dates

          Possible values:
          - 20250201: SysMLv2/KerML Release or Beta4

          [default: 20250201]

      --release-custom <YYYYMMDD>
          Choose a custom release of the SysML v2 or KerML metamodel

      --set-custom <METAMODEL>
          Set a custom metamodel. To set a SysML v2 or KerML metamodel, use `--set`

      --clear


Global options:
[...]
```
- include a bit more info about Sysand in `sysand --help` by using a custom clap help template (based on [default template](https://github.com/clap-rs/clap/blob/8d87e70789ed7832aa93473779d248090712d66b/clap_builder/src/output/help_template.rs#L65)):
```console
$ sysand --help
A project and package manager for SysML v2 and KerML

Documentation:
<https://docs.sysand.org/>
Package index and more information:
<https://beta.sysand.org/>
Project repository:
<https://github.com/sensmetry/sysand/>

Usage: sysand [OPTIONS] <COMMAND>

Commands:
[...]

Options:
[...]

Global options:
[...]

sysand v0.0.6
Developed by: Sensmetry <opensource@sensmetry.com>
```
- mention project metadata editing in `sysand info --help`:
```console
$ sysand info --help
Describe or modify the current project or resolve
and describe a project at a specified path or IRI/URL
[...]
```

## Docs

- add guide on how to format text (errors, log messages, docstrings) to DEVELOPMENT.md

## Tests

- test setting metamodel in various ways

### CODE REVIEW

File: core/src/model.rs [hunk 1]
```diff
@@ -200,16 +200,135 @@ impl TryFrom<InterchangeProjectInfoRaw> for InterchangeProjectInfo {
...
+/// - MD2, MD4, MD5, MD6
+/// - ADLER32
+// TODO: why is SHA512 missing? Also SHA256 vs SHA-384
+#[derive(Clone, Copy, Debug, Deserialize, Serialize, PartialEq, Eq)]
+#[serde(try_from = "String", into = "&str")]
+#[cfg_attr(feature = "python", pyclass(eq, eq_int))]
+pub enum KerMlChecksumAlg {
+    /// No checksum. Non-standard,
+    /// must not be used in real projects
+    None,
```
Comment (tilowiklundSensmetry) [inline core/src/model.rs]: We expect it to be used when you want to note the presence of a file (to be checksum-ed during build) in a volatile state (e.g. in Git trunk).

File: core/src/model.rs [hunk 2]
```diff
@@ -200,16 +200,135 @@ impl TryFrom<InterchangeProjectInfoRaw> for InterchangeProjectInfo {
...
 #[cfg_attr(feature = "python", derive(FromPyObject, IntoPyObject))]
 #[serde(rename_all = "camelCase")]
 pub struct InterchangeProjectChecksum {
     pub value: String,
-    // SHA1, SHA224, SHA256, SHA-384, SHA3-256, SHA3-384, SHA3-512 [SHS]
-    // BLAKE2b-256, BLAKE2b-384, BLAKE2b-512, BLAKE3 [BLAKE]
-    // MD2, MD4, MD5, MD6 [MD]
-    // ADLER32 [ADLER]
-    pub algorithm: String,
+    pub algorithm: KerMlChecksumAlg,
```
Comment (tilowiklundSensmetry) [inline core/src/model.rs]: Could we split this type into a `raw` and a non-`raw` version (matching the other types here). This way we can have better round-tripping and we can operate on partially malformed files (say, for example, we add something like `sysand recalc-checksum --alg XYZ`, which would be expected to correct an incorrect checksum field).

File: sysand/src/cli.rs [hunk 3]
```diff
@@ -1115,3 +1142,109 @@ impl GlobalOptions {
...
+}
+
+#[allow(non_camel_case_types)]
+#[derive(Default, Debug, Clone, Copy, PartialEq, Eq)]
+pub enum MetamodelVersion {
+    Beta1_20230201 = 20230201,
+    Beta2_20240201 = 20240201,
+    #[default]
+    Release_20250201 = 20250201,
+}
```
[the remark this answers is not in the document]
Comment (andrius-puksta-sensmetry) [reply sysand/src/cli.rs]: Removed pre-releases in https://github.com/sensmetry/sysand/pull/128/commits/73a8b92ac8c2d258b7791038d190823ece861b00
